version: '3.8'

services:

  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://ckorir_zxa5_user:vdw07HOB6rNDuONtXiA16GDOIrgIq7sd@postgres/ckorir_zxa5
    depends_on:
      - postgres

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://ckorir_zxa5_user:vdw07HOB6rNDuONtXiA16GDOIrgIq7sd@postgres/ckorir_zxa5
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ckorir_zxa5
      POSTGRES_USER: ckorir_zxa5_user
      POSTGRES_PASSWORD: vdw07HOB6rNDuONtXiA16GDOIrgIq7sd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
